const {test,expect}=require('@playwright/test');
const AxeBuilder=require('@axe-core/playwright').default;

test('home prioritizes official status and separates local, forecast and weather',async({page})=>{await page.goto('/?lang=en');await expect(page.getByRole('heading',{name:'Air quality now'})).toBeVisible();await expect(page.getByText('OFFICIAL AREA STATUS')).toBeVisible();await expect(page.getByText('LOCAL SENSOR NETWORK')).toBeVisible();await expect(page.getByText(/CAMS Global/).first()).toBeVisible();await expect(page.getByText('Air context')).toBeVisible();const width=await page.locator('.app-shell').evaluate(e=>e.getBoundingClientRect().width);expect(width).toBeLessThanOrEqual(page.viewportSize().width);});
test('all pages use separate mobile and desktop presentations',async({page},testInfo)=>{const desktop=testInfo.project.name.startsWith('desktop');for(const path of['/?lang=en','/stations.php?lang=en','/station.php?code=air4thai%3A36t&lang=en','/alerts.php?lang=en','/offline.php?lang=en']){await page.goto(path);const shellWidth=await page.locator('.app-shell').evaluate(e=>e.getBoundingClientRect().width);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize().width);if(desktop)expect(shellWidth).toBeGreaterThan(900);else expect(shellWidth).toBeLessThanOrEqual(430);if(path.startsWith('/offline.php'))continue;await expect(page.locator('.desktop-nav')).toHaveCSS('display',desktop?'flex':'none');await expect(page.locator('.bottom-nav')).toHaveCSS('display',desktop?'none':'grid');}});
test('Thai language and theme preference work',async({page})=>{await page.goto('/?lang=th');await expect(page.getByRole('heading',{name:'คุณภาพอากาศขณะนี้'})).toBeVisible();await page.locator('#theme-toggle').click();await expect.poll(()=>page.evaluate(()=>localStorage.getItem('cmaw-theme'))).not.toBeNull();});
test('home station persists and changes provider presentation when local exists',async({page})=>{await page.goto('/?lang=en');const options=await page.locator('#home-station-select option').evaluateAll(nodes=>nodes.map(n=>n.value));const local=options.find(value=>value.startsWith('dustboy:'));const chosen=local||options.at(-1);await page.locator('#home-station-select').selectOption(chosen);await expect.poll(()=>page.evaluate(()=>localStorage.getItem('cmaw-home-station'))).toBe(chosen);await page.reload();await expect(page.locator('#home-station-select')).toHaveValue(chosen);if(local){await expect(page.locator('#selected-station-card')).toHaveAttribute('data-classification','supplementary');await expect(page.locator('#primary-reading-label')).toHaveText('PM2.5 µg/m³');await expect(page.locator('#primary-source')).toContainText('DustBoy');}});
test('station filters, map markers and saved view work',async({page})=>{await page.goto('/stations.php?lang=en');await expect(page.locator('.station-card')).not.toHaveCount(0);await page.getByRole('button',{name:'Official',exact:true}).click();await expect(page.locator('.station-card:not([hidden])')).not.toHaveCount(0);await page.getByRole('button',{name:'Map',exact:true}).click();await expect(page.locator('#station-map')).toBeVisible();await expect(page.locator('.leaflet-marker-icon')).not.toHaveCount(0);await page.reload();await expect(page.locator('[data-view-panel="map"]')).toBeVisible();});
test('map clusters at least 100 loaded stations and passes axe without exclusions',async({page})=>{await page.goto('/stations.php?lang=en');await page.evaluate(()=>{const host=document.querySelector('#map-station-data');const seed=host?.querySelector('[data-map-station]');if(!host||!seed)return;const needed=Math.max(0,100-host.querySelectorAll('[data-map-station]').length);for(let index=0;index<needed;index++){const node=seed.cloneNode(true);node.dataset.mapStation=`synthetic:${index}`;node.dataset.name=`Synthetic station ${index}`;node.dataset.latitude=String(18.70+(index%10)*0.01);node.dataset.longitude=String(98.90+(index%9)*0.01);host.append(node);}});await page.getByRole('button',{name:'Map',exact:true}).click();await expect(page.locator('#station-map')).toHaveAttribute('data-marker-count','100');const result=await new AxeBuilder({page}).include('[data-view-panel="map"]').analyze();expect(result.violations).toEqual([]);});
test('station detail supports all history periods',async({page})=>{await page.goto('/station.php?code=air4thai%3A36t&lang=en');await expect(page.locator('#history-period')).toBeVisible();for(const period of['24h','72h','7d','30d','90d','1y','5y']){await page.locator('#history-period').selectOption(period);await expect(page.locator('#aggregation-label')).not.toBeEmpty();}});
test('current and stations APIs expose source metadata without raw payload',async({request})=>{const current=await request.get('/api/current.php?lang=en');expect(current.ok()).toBeTruthy();const body=await current.json();expect(body.data.stations[0].source).toMatchObject({provider:'air4thai',classification:'official',official:true});expect(body.data).toHaveProperty('local_sensor_summary');expect(body.data.local_sensor_summary).toHaveProperty('valid_pm25_count');expect(body.data).toHaveProperty('weather');expect(JSON.stringify(body)).not.toContain('raw_payload');const invalid=await request.get('/api/history.php?station=air4thai%3A36t&period=bad');expect(invalid.status()).toBeGreaterThanOrEqual(400);});
test('alerts and push capability render truthfully',async({page})=>{await page.goto('/alerts.php?lang=en');await expect(page.getByRole('heading',{name:'Air-quality alerts'})).toBeVisible();await expect(page.locator('#push-settings')).toHaveAttribute('data-enabled',/true|false/);});
test('API failure keeps server-rendered verified values',async({page})=>{await page.route('**/api/current.php**',route=>route.abort());await page.goto('/');await expect(page.locator('#primary-title')).not.toBeEmpty();await expect(page.locator('#offline-banner')).toBeVisible();});
test('offline snapshot records actual save time',async({page})=>{await page.goto('/');await expect.poll(()=>page.evaluate(()=>{const value=localStorage.getItem('cmaw-offline-snapshot-'+document.body.dataset.language);if(!value)return false;const parsed=JSON.parse(value);return Boolean(parsed.snapshot_saved_at&&parsed.payload);})).toBe(true);});
test('keyboard, accessibility and horizontal fit',async({page})=>{await page.goto('/');await page.keyboard.press('Tab');await expect(page.locator(':focus')).toBeVisible();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);expect(overflow).toBeFalsy();const result=await new AxeBuilder({page}).analyze();expect(result.violations).toEqual([]);});
test('service worker uses V1.1 shell and excludes APIs and OSM tiles',async({page})=>{await page.goto('/sw.js');const text=await page.locator('body').innerText();expect(text).toContain('chiang-mai-air-watch-shell-v1.1.2');expect(text).toContain('api/');expect(text).toContain('tile.openstreetmap.org');});
