<?php
// Senast uppdaterad: 2026-09-05 14:10 Asia/Bangkok | Version 1.11 | KlⒶssⓔ & Ⓐberg
declare(strict_types=1);
namespace ChiangMaiAirWatch\Tests\Integration;

use ChiangMaiAirWatch\Repositories\AlertRepository;
use ChiangMaiAirWatch\Repositories\MeasurementRepository;
use ChiangMaiAirWatch\Repositories\ProviderHealthRepository;
use ChiangMaiAirWatch\Repositories\DailySummaryRepository;
use ChiangMaiAirWatch\Repositories\StationRepository;
use ChiangMaiAirWatch\Services\DashboardService;
use ChiangMaiAirWatch\Services\DustBoyRequestLedger;
use ChiangMaiAirWatch\Services\DustBoyStationSync;
use ChiangMaiAirWatch\Config;
use ChiangMaiAirWatch\Services\AlertManager;
use ChiangMaiAirWatch\Services\RateLimiter;
use ChiangMaiAirWatch\Services\HealthService;
use ChiangMaiAirWatch\Services\RetentionService;
use DateTimeImmutable;
use DateTimeZone;
use PDO;
use PHPUnit\Framework\TestCase;

final class AirLifecycleTest extends TestCase
{
    private PDO$db;private int$stationId;
    protected function setUp():void
    {
        $dsn=getenv('CMAW_TEST_DSN')?:'';if($dsn==='')self::markTestSkipped('Isolated MariaDB test credentials are not loaded.');
        $this->db=new PDO($dsn,getenv('CMAW_TEST_DB_USER')?:'',getenv('CMAW_TEST_DB_PASSWORD')?:'',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
        $this->db->exec('SET FOREIGN_KEY_CHECKS=0');foreach(['push_deliveries','notification_outbox','push_subscriptions','api_rate_limits','alert_stations','alert_events','alerts','air_quality_transitions','risk_state','forecast_state','air_forecast_points','forecast_runs','forecast_zones','daily_air_summary','provider_api_requests','weather_state','measurement_revisions','station_state','measurements','collector_runs','provider_health','stations']as$t)$this->db->exec("TRUNCATE TABLE $t");$this->db->exec('SET FOREIGN_KEY_CHECKS=1');
        $this->db->exec("INSERT INTO stations(provider,provider_station_code,display_name_en,display_name_th,area_en,area_th,province_en,province_th,district_en,district_th,latitude,longitude,is_primary,affects_official_status,enabled)VALUES('air4thai','36t','Yupparaj','ยุพราช','Mueang','เมือง','Chiang Mai','เชียงใหม่','Mueang','เมือง',18.7909,98.99,1,1,1)");$this->stationId=(int)$this->db->lastInsertId();
    }
    public function testDedupCorrectionRevisionAndNullPersistence():void{$repo=new MeasurementRepository($this->db);$point=$this->point(20,12.5);self::assertSame('inserted',$repo->store($point,$this->stationId));self::assertSame('unchanged',$repo->store($point,$this->stationId));$corrected=$this->point(21,null);self::assertSame('updated',$repo->store($corrected,$this->stationId));self::assertSame(1,(int)$this->db->query('SELECT COUNT(*) FROM measurements')->fetchColumn());self::assertSame(1,(int)$this->db->query('SELECT COUNT(*) FROM measurement_revisions')->fetchColumn());self::assertNull($this->db->query('SELECT pm25_ug_m3 FROM measurements')->fetchColumn());}
    public function testFreshnessStatesAndTrends():void{$repo=new MeasurementRepository($this->db);foreach([["2026-09-02 09:00:00",10],["2026-09-02 11:00:00",12],["2026-09-02 12:00:00",15]]as[$at,$value]){$p=$this->point(20,$value);$p['measured_at']=$at;$p['source_measured_at']=$at;$repo->store($p,$this->stationId);}$repo->refreshState($this->stationId,new DateTimeImmutable('2026-09-02 12:30:00',new DateTimeZone('UTC')));$state=$this->db->query('SELECT * FROM station_state')->fetch();self::assertSame('live',$state['freshness_status']);self::assertSame(3.0,(float)$state['change_1h_pm25']);self::assertSame(5.0,(float)$state['change_3h_pm25']);$repo->refreshState($this->stationId,new DateTimeImmutable('2026-09-02 15:01:00',new DateTimeZone('UTC')));self::assertSame('stale',$this->db->query('SELECT freshness_status FROM station_state')->fetchColumn());}
    public function testAlertEscalationDebounceRecoveryAndOutbox():void{$repo=new AlertRepository($this->db);$manager=new AlertManager($this->db,$repo);$now=new DateTimeImmutable('2026-09-02 00:00:00',new DateTimeZone('UTC'));$manager->reconcile($this->risk('unhealthy'),$now);$manager->reconcile($this->risk('unhealthy'),$now->modify('+5 minutes'));self::assertSame(1,(int)$this->db->query('SELECT COUNT(*) FROM notification_outbox')->fetchColumn());$manager->reconcile($this->risk('very_unhealthy'),$now->modify('+6 minutes'));self::assertSame('very_unhealthy',$repo->active()['severity']);self::assertSame(2,(int)$this->db->query('SELECT COUNT(*) FROM notification_outbox')->fetchColumn());$manager->reconcile($this->risk('normal'),$now->modify('+10 minutes'));$manager->reconcile($this->risk('normal'),$now->modify('+99 minutes'));self::assertNotNull($repo->active());$manager->reconcile($this->risk('normal'),$now->modify('+100 minutes'));self::assertNull($repo->active());self::assertSame(3,(int)$this->db->query('SELECT COUNT(*) FROM notification_outbox')->fetchColumn());}
    public function testUnknownDoesNotClearAndRateLimitIsAtomic():void{Config::overrideForTests(['security'=>['rate_limit_key'=>'isolated-test-secret']]);$repo=new AlertRepository($this->db);$manager=new AlertManager($this->db,$repo);$now=new DateTimeImmutable('2026-09-02 00:00:00',new DateTimeZone('UTC'));$manager->reconcile($this->risk('unhealthy'),$now);$manager->reconcile($this->risk('unknown'),$now->modify('+180 minutes'));self::assertNotNull($repo->active());$limit=new RateLimiter($this->db);self::assertTrue($limit->consume('test','127.0.0.1',2,60)['allowed']);self::assertTrue($limit->consume('test','127.0.0.1',2,60)['allowed']);self::assertFalse($limit->consume('test','127.0.0.1',2,60)['allowed']);}
    public function testProviderHealthRecoversAfterFailure():void{$repo=new ProviderHealthRepository($this->db);$repo->failure('air4thai','observation','HTTP_STATUS','sanitized');$repo->failure('air4thai','observation','HTTP_STATUS','sanitized');self::assertSame(2,(int)$repo->get('air4thai')['consecutive_failures']);$repo->success('air4thai','observation');self::assertSame(0,(int)$repo->get('air4thai')['consecutive_failures']);}
    public function testHealthDegradesForMissingCollectorsObservationsAndForecast():void{$health=(new HealthService($this->db))->evaluate(new DateTimeImmutable('2026-09-02 12:00:00',new DateTimeZone('UTC')));self::assertSame('degraded',$health['status']);self::assertContains('OFFICIAL_OBSERVATION_TOO_OLD',$health['reasons']);self::assertContains('FORECAST_INSUFFICIENT',$health['reasons']);}
    public function testDailySummaryRebuildAndLongHistoryAreIdempotent():void{$repo=new MeasurementRepository($this->db);foreach([['2026-01-01 01:00:00',10],['2026-01-01 03:00:00',20],['2026-01-08 02:00:00',30]]as[$time,$value]){$point=$this->point(20,$value);$point['measured_at']=$time;$point['source_measured_at']=$time;$repo->store($point,$this->stationId);}$summary=new DailySummaryRepository($this->db);$summary->rebuild('2026-01-01','2026-01-08',$this->stationId);$summary->rebuild('2026-01-01','2026-01-08',$this->stationId);self::assertSame(2,(int)$this->db->query('SELECT COUNT(*) FROM daily_air_summary')->fetchColumn());self::assertSame(15.0,(float)$this->db->query("SELECT pm25_avg FROM daily_air_summary WHERE summary_date='2026-01-01'")->fetchColumn());self::assertCount(2,$repo->history($this->stationId,'1y'));self::assertCount(2,$repo->history($this->stationId,'5y'));}
    public function testLocalSummarySeparatesLiveSensorsFromValidPm25Readings():void{$repo=new MeasurementRepository($this->db);$now=gmdate('Y-m-d H:i:s');foreach([['a',10],['b',20],['c',null]]as[$code,$value]){$this->db->exec("INSERT INTO stations(provider,provider_station_code,display_name_en,display_name_th,area_en,area_th,province_en,province_th,district_en,district_th,latitude,longitude,is_primary,affects_official_status,enabled)VALUES('dustboy','$code','D','D','M','M','C','C','M','M',18.79,98.99,0,0,1)");$id=(int)$this->db->lastInsertId();$point=$this->point(null,$value);$point['provider']='dustboy';$point['provider_station_code']=$code;$point['source_status']='supplementary';$point['measured_at']=$now;$point['source_measured_at']=$now;$repo->store($point,$id);$repo->refreshState($id);} $summary=(new DashboardService($this->db))->localSensorSummary();self::assertSame(3,$summary['live_count']);self::assertSame(2,$summary['valid_pm25_count']);self::assertSame(15.0,$summary['median_pm25']);self::assertSame(10.0,$summary['min_pm25']);self::assertSame(20.0,$summary['max_pm25']);}
    public function testOfficialHealthCannotBeMaskedByFreshDustBoy():void{$this->db->exec("INSERT INTO stations(provider,provider_station_code,display_name_en,display_name_th,area_en,area_th,province_en,province_th,district_en,district_th,latitude,longitude,is_primary,affects_official_status,enabled)VALUES('dustboy','fresh','D','D','M','M','C','C','M','M',18.79,98.99,0,0,1)");$id=(int)$this->db->lastInsertId();$point=$this->point(null,12);$point['provider']='dustboy';$point['provider_station_code']='fresh';$point['source_status']='supplementary';$point['measured_at']='2026-09-02 12:00:00';(new MeasurementRepository($this->db))->store($point,$id);$health=(new HealthService($this->db))->evaluate(new DateTimeImmutable('2026-09-02 12:10:00',new DateTimeZone('UTC')));self::assertContains('OFFICIAL_OBSERVATION_TOO_OLD',$health['reasons']);self::assertSame('2026-09-02 12:00:00',$health['latest_supplementary_observation_at']);}
    public function testDustBoyRequestLedgerDueAndRollingLimit():void{Config::overrideForTests(['providers'=>['dustboy'=>['minimum_fetch_interval_minutes'=>55,'maximum_requests_per_hour'=>2]]]);$ledger=new DustBoyRequestLedger($this->db);self::assertTrue($ledger->latestIsDue());$first=$ledger->reserve('latest');$ledger->finish($first,'success');self::assertFalse($ledger->latestIsDue());$second=$ledger->reserve('history_30d');$ledger->finish($second,'success');$this->expectException(\ChiangMaiAirWatch\Providers\ProviderException::class);$ledger->reserve('history_1y');}
    public function testLocalRequestLedgerExhaustionSkipsLatestWithoutAnotherRequest():void{Config::overrideForTests(['providers'=>['dustboy'=>['maximum_requests_per_hour'=>1]]]);$ledger=new DustBoyRequestLedger($this->db);$id=$ledger->reserve('history_30d');$ledger->finish($id,'success');self::assertNull($ledger->reserveLatestIfAvailable());self::assertSame(1,(int)$this->db->query("SELECT COUNT(*) FROM provider_api_requests")->fetchColumn());}
    public function testHealthReportsEnabledDustBoyAndWeatherDegradation():void{Config::overrideForTests(['providers'=>['observations'=>['air4thai','dustboy'],'dustboy'=>['enabled'=>true],'openmeteo_weather'=>['enabled'=>true]]]);$healthRepo=new ProviderHealthRepository($this->db);$healthRepo->failure('dustboy','observation','UPSTREAM_HTTP_ERROR','sanitized');$healthRepo->failure('openmeteo_weather','weather','UPSTREAM_HTTP_ERROR','sanitized');$health=(new HealthService($this->db))->evaluate(new DateTimeImmutable('2026-09-02 12:00:00',new DateTimeZone('UTC')));self::assertSame('degraded',$health['status']);self::assertContains('SUPPLEMENTARY_OBSERVATION_TOO_OLD',$health['reasons']);self::assertContains('WEATHER_TOO_OLD',$health['reasons']);self::assertContains('PROVIDER_DUSTBOY_FAILED',$health['reasons']);self::assertContains('PROVIDER_OPENMETEO_WEATHER_FAILED',$health['reasons']);}
    public function testRetentionDeletesExpiredRowsAndKeepsCurrentRows():void{Config::overrideForTests(['retention'=>['measurement_months'=>24,'daily_summary_years'=>10,'provider_request_days'=>2]]);$repo=new MeasurementRepository($this->db);foreach([['2020-01-01 00:00:00',10], [gmdate('Y-m-d H:i:s'),20]]as[$time,$value]){$point=$this->point(20,$value);$point['measured_at']=$time;$point['source_measured_at']=$time;$repo->store($point,$this->stationId);}$this->db->exec("INSERT INTO daily_air_summary(station_id,summary_date,samples,created_at,updated_at) VALUES($this->stationId,'2010-01-01',1,UTC_TIMESTAMP(),UTC_TIMESTAMP()),($this->stationId,UTC_DATE(),1,UTC_TIMESTAMP(),UTC_TIMESTAMP())");$this->db->exec("INSERT INTO provider_api_requests(provider,request_class,requested_at,outcome) VALUES('dustboy','latest','2020-01-01 00:00:00','success'),('dustboy','latest',UTC_TIMESTAMP(),'success')");$deleted=(new RetentionService($this->db))->purge();self::assertSame(1,$deleted['measurements_deleted']);self::assertSame(1,$deleted['daily_summaries_deleted']);self::assertSame(1,$deleted['provider_requests_deleted']);self::assertSame(1,(int)$this->db->query('SELECT COUNT(*) FROM measurements')->fetchColumn());self::assertSame(1,(int)$this->db->query('SELECT COUNT(*) FROM daily_air_summary')->fetchColumn());self::assertSame(1,(int)$this->db->query('SELECT COUNT(*) FROM provider_api_requests')->fetchColumn());}
    public function testDustBoyStationSyncDryRunApplyAndDuplicateAreIdempotent():void{$service=new DustBoyStationSync(['center'=>['latitude'=>18.7883,'longitude'=>98.9853],'radius_km'=>15,'maximum_stations'=>10,'station_ids'=>[]]);$rows=[['id'=>'5050','name'=>'','latitude'=>18.79,'longitude'=>98.99,'dustboy_id'=>'DB-5050','model'=>'X','version'=>'1'],['id'=>'far','name'=>'Far','latitude'=>20.0,'longitude'=>100.0]];$repo=new StationRepository($this->db);$before=(int)$this->db->query("SELECT COUNT(*) FROM stations WHERE provider='dustboy'")->fetchColumn();$dry=$service->synchronize($rows,$repo,false);self::assertSame('dry-run',$dry['mode']);self::assertSame($before,(int)$this->db->query("SELECT COUNT(*) FROM stations WHERE provider='dustboy'")->fetchColumn());$first=$service->synchronize($rows,$repo,true);$second=$service->synchronize($rows,$repo,true);$changed=$rows;$changed[0]['name']='Changed';$third=$service->synchronize($changed,$repo,true);self::assertSame(1,$first['changes']['inserted']);self::assertSame(1,$second['changes']['unchanged']);self::assertSame(0,$second['changes']['updated']);self::assertSame(1,$third['changes']['updated']);self::assertSame(1,(int)$this->db->query("SELECT COUNT(*) FROM stations WHERE provider='dustboy'")->fetchColumn());$station=$repo->byPublicId('dustboy:5050');self::assertSame('Changed',$station['display_name_en']);self::assertSame(0,(int)$station['affects_official_status']);}
    private function point(?int$aqi,?float$pm25):array{return['provider'=>'air4thai','provider_station_code'=>'36t','measured_at'=>'2026-09-02 12:00:00','source_measured_at'=>'2026-09-02 19:00','source_aqi'=>$aqi,'source_aqi_scale'=>$aqi===null?null:'TH_AQI_2023','source_aqi_pollutant'=>$aqi===null?null:'PM25','pm25_ug_m3'=>$pm25,'pm10_ug_m3'=>null,'pm25_unit'=>'µg/m³','pm10_unit'=>'µg/m³','ozone_value'=>null,'ozone_unit'=>'ppb','carbon_monoxide_value'=>null,'carbon_monoxide_unit'=>'ppm','nitrogen_dioxide_value'=>null,'nitrogen_dioxide_unit'=>'ppb','sulphur_dioxide_value'=>null,'sulphur_dioxide_unit'=>'ppb','temperature_c'=>null,'humidity_pct'=>null,'source_status'=>'verified','raw_payload'=>['test'=>true,'aqi'=>$aqi,'pm25'=>$pm25]];}
    private function risk(string$severity):array{return['severity'=>$severity,'reason_codes'=>['TEST'],'message_key'=>'alert.message.'.$severity,'context'=>['station_ids'=>[$this->stationId]]];}
}
