<?php
// Senast uppdaterad: 2026-09-05 14:00 Asia/Bangkok | Version 1.11 | KlⒶssⓔ & Ⓐberg
return [
'home.valid_pm25_sensors'=>'Valid live PM2.5 readings',
'app.name'=>'Chiang Mai Air Watch','app.tagline'=>'Official observations and modelled air-quality outlook','nav.home'=>'Home','nav.stations'=>'Stations','nav.alerts'=>'Alerts','language.switch'=>'ภาษาไทย','language.label'=>'Change language to Thai','a11y.skip'=>'Skip to content','a11y.primary_nav'=>'Primary navigation','a11y.theme'=>'Theme',
'common.updated'=>'Updated {time}','common.no_data'=>'No data available','common.details'=>'View details','common.current'=>'Current','common.offline'=>'OFFLINE · showing the last verified snapshot','common.update_failed'=>'COULD NOT REFRESH · Last verified values remain visible.','common.data_stale'=>'UPDATE DELAYED · Some readings are older than expected.','common.chart_failed'=>'Chart update failed; the last verified chart remains visible.','common.last_24h'=>'Last 24 hours','common.next_24h'=>'Next 24 hours','common.saved_at'=>'Snapshot saved {time}','common.disclaimer'=>'General air-quality information only, not individual medical advice. Follow official public-health guidance.',
'home.eyebrow'=>'MUEANG CHIANG MAI · THAILAND','home.title'=>'Air quality now','home.station_picker'=>'Home station','home.selected_station'=>'Selected station','home.change'=>'1-hour PM2.5 trend','home.aqi_unavailable'=>'AQI unavailable','home.area_status'=>'Official area status','home.official_area_status'=>'OFFICIAL AREA STATUS','home.official_chart'=>'Official station history','home.chart_title'=>'PM2.5 and PM10 history','home.chart_empty'=>'History will appear after collection.','home.station_status'=>'All stations','home.local_network'=>'LOCAL SENSOR NETWORK','home.local_empty'=>'No current local sensor readings are available.','home.sensors_online'=>'sensors online','home.delayed_sensors'=>'Delayed / stale','home.median_pm25'=>'Median PM2.5','home.lowest_pm25'=>'Lowest','home.highest_pm25'=>'Highest','home.median_change'=>'Median 1-hour change','home.forecast_title'=>'Model forecast risk','home.attribution'=>'Air quality model data by Open-Meteo.com (CAMS Global)','home.weather_title'=>'Air context','home.wind'=>'Wind','home.gusts'=>'Gusts','home.rain'=>'Rain','home.temperature'=>'Temperature','home.weather_unavailable'=>'Weather context is temporarily unavailable.','home.weather_attribution'=>'Weather data: Open-Meteo','home.advisory'=>'Combined advice',
'station.title'=>'Air-quality stations','station.subtitle'=>'Official Air4Thai and supplementary CMU DustBoy observations in Mueang Chiang Mai.','station.measured'=>'Measured','station.set_home'=>'Set as home station','station.view_label'=>'Station view','station.view_list'=>'List','station.view_map'=>'Map','station.map_title'=>'Station map','station.map_note'=>'Map © OpenStreetMap contributors. Tiles require internet and are not cached.','station.history'=>'{code} history','station.filter_label'=>'Filter stations','station.filter_all'=>'All','station.filter_official'=>'Official','station.filter_local'=>'Local','station.official'=>'OFFICIAL','station.local'=>'LOCAL SENSOR','station.pm25_legend'=>'Local marker colours show PM2.5 concentration, not AQI.',
'source.air4thai'=>'Air4Thai / PCD','source.dustboy'=>'CMU DustBoy / CMU CCDC','source.openmeteo_weather'=>'Open-Meteo','pm25.band.low'=>'Low PM2.5','pm25.band.moderate'=>'Moderate PM2.5','pm25.band.high'=>'High PM2.5','pm25.band.very_high'=>'Very high PM2.5','pm25.band.unknown'=>'PM2.5 unavailable',
'alerts.title'=>'Air-quality alerts','alerts.subtitle'=>'Alerts open at unhealthy, escalate immediately, and recover after 90 minutes below threshold.','alerts.none'=>'No air-quality alert incidents have opened.','alerts.active'=>'Active','alerts.cleared'=>'Cleared','push.setting_title'=>'Air-quality notifications','push.setting_body'=>'Receive unhealthy, very unhealthy, and one recovery notification per incident.','push.enable'=>'Enable notifications','push.disable'=>'Disable notifications','push.not_requested'=>'Notifications are off.','push.enabled'=>'Notifications enabled.','push.denied'=>'Notifications are blocked in browser settings.','push.unsupported'=>'Notifications are not supported here.','push.install_required'=>'Add this app to your Home Screen first.','push.error'=>'Notification settings could not be updated.',
'air.status.very_good'=>'Very good','air.status.good'=>'Good','air.status.moderate'=>'Moderate','air.status.unhealthy'=>'Unhealthy','air.status.very_unhealthy'=>'Very unhealthy','air.status.unknown'=>'AQI unavailable','forecast.low'=>'Modelled PM2.5 risk is low.','forecast.moderate'=>'Modelled PM2.5 risk is moderate.','forecast.high'=>'Modelled PM2.5 risk is high.','forecast.very_high'=>'Modelled PM2.5 risk is very high.','forecast.unknown'=>'The model outlook is unavailable.','forecast.direction.improving'=>'Conditions are modelled to improve.','forecast.direction.worsening'=>'Conditions are modelled to worsen.','forecast.direction.stable'=>'Conditions are modelled to remain broadly stable.','forecast.direction.unknown'=>'A direction cannot yet be assessed.',
'advisory.normal'=>'Current official readings and the model outlook do not indicate heightened air-quality risk.','advisory.watch'=>'Keep an eye on updates; either observations or the model outlook are elevated.','advisory.warning'=>'Reduce avoidable smoke exposure and follow official public-health updates.','advisory.critical'=>'Very poor air quality is reported or modelled. Follow official health guidance.','advisory.unknown'=>'Combined advice needs a current official observation and model forecast.','alert.title.unhealthy'=>'Unhealthy air quality','alert.title.very_unhealthy'=>'Very unhealthy air quality','alert.message.unhealthy'=>'An official station reports unhealthy air quality.','alert.message.very_unhealthy'=>'An official station reports very unhealthy air quality.','alert.message.normal'=>'The active air-quality incident has recovered.',
'severity.normal'=>'Normal','severity.watch'=>'Watch','severity.warning'=>'Warning','severity.critical'=>'Critical','severity.unhealthy'=>'Unhealthy','severity.very_unhealthy'=>'Very unhealthy','severity.unknown'=>'Update pending','severity.low'=>'Low','severity.moderate'=>'Moderate','severity.high'=>'High','severity.very_high'=>'Very high','freshness.live'=>'LIVE','freshness.delayed'=>'DELAYED','freshness.stale'=>'STALE','freshness.offline'=>'OFFLINE','freshness.current'=>'CURRENT','freshness.aging'=>'AGING',
'push.title.unhealthy'=>'Chiang Mai Air Watch — Unhealthy','push.title.very_unhealthy'=>'Chiang Mai Air Watch — Very unhealthy','push.title.cleared'=>'Chiang Mai Air Watch — Recovered','push.body.unhealthy'=>'An official station reports unhealthy air quality.','push.body.very_unhealthy'=>'An official station reports very unhealthy air quality.','push.body.cleared'=>'The active air-quality incident has recovered.',
'error.title'=>'Unable to load data','error.body'=>'The latest stored air-quality information is temporarily unavailable.','error.api.invalid_station'=>'The requested station is not supported.','error.api.invalid_period'=>'The requested period is not supported.','error.api.invalid_language'=>'The requested language is not supported.','error.api.station_not_found'=>'The requested station is unavailable.','error.api.method_not_allowed'=>'This request method is not supported.','error.api.invalid_content_type'=>'This endpoint requires JSON.','error.api.invalid_origin'=>'This request origin is not allowed.','error.api.request_too_large'=>'The request body is too large.','error.api.invalid_json'=>'The request body is not valid JSON.','error.api.invalid_subscription'=>'The notification subscription is invalid.','error.api.push_disabled'=>'Notifications are not enabled on this server.','error.api.rate_limited'=>'Too many notification requests. Try again later.','error.api.internal'=>'The requested data is temporarily unavailable.','offline.title'=>'You are offline','offline.body'=>'Reconnect to retrieve current air-quality information.','theme.system'=>'System','theme.light'=>'Light','theme.dark'=>'Dark','theme.change'=>'Theme: {mode}. Tap to change.'
,'home.humidity'=>'Humidity',
];
