<?php
// Senast uppdaterad: 2026-09-05 14:00 Asia/Bangkok | Version 1.11 | KlⒶssⓔ & Ⓐberg
return [
'home.valid_pm25_sensors'=>'ค่าฝุ่น PM2.5 สดที่ใช้ได้',
'app.name'=>'เฝ้าระวังคุณภาพอากาศเชียงใหม่','app.tagline'=>'ข้อมูลตรวจวัดทางการและแนวโน้มคุณภาพอากาศจากแบบจำลอง','nav.home'=>'หน้าหลัก','nav.stations'=>'สถานี','nav.alerts'=>'แจ้งเตือน','language.switch'=>'English','language.label'=>'เปลี่ยนภาษาเป็นอังกฤษ','a11y.skip'=>'ข้ามไปยังเนื้อหา','a11y.primary_nav'=>'เมนูหลัก','a11y.theme'=>'ธีม',
'common.updated'=>'อัปเดต {time}','common.no_data'=>'ไม่มีข้อมูล','common.details'=>'ดูรายละเอียด','common.current'=>'ปัจจุบัน','common.offline'=>'ออฟไลน์ · แสดงข้อมูลล่าสุดที่ตรวจสอบแล้ว','common.update_failed'=>'อัปเดตไม่ได้ · ยังคงแสดงข้อมูลล่าสุดที่ตรวจสอบแล้ว','common.data_stale'=>'ข้อมูลล่าช้า · ค่าบางส่วนเก่ากว่าที่คาด','common.chart_failed'=>'อัปเดตกราฟไม่ได้ ยังคงแสดงกราฟล่าสุด','common.last_24h'=>'24 ชั่วโมงที่ผ่านมา','common.next_24h'=>'24 ชั่วโมงข้างหน้า','common.saved_at'=>'บันทึกข้อมูลเมื่อ {time}','common.disclaimer'=>'ข้อมูลคุณภาพอากาศทั่วไป ไม่ใช่คำแนะนำทางการแพทย์เฉพาะบุคคล โปรดปฏิบัติตามคำแนะนำของหน่วยงานสาธารณสุข',
'home.eyebrow'=>'อำเภอเมืองเชียงใหม่ · ประเทศไทย','home.title'=>'คุณภาพอากาศขณะนี้','home.station_picker'=>'สถานีหลัก','home.selected_station'=>'สถานีที่เลือก','home.change'=>'แนวโน้ม PM2.5 1 ชั่วโมง','home.aqi_unavailable'=>'ไม่มีค่า AQI','home.area_status'=>'สถานะพื้นที่ทางการ','home.official_area_status'=>'สถานะพื้นที่ทางการ','home.official_chart'=>'ประวัติสถานีทางการ','home.chart_title'=>'ประวัติ PM2.5 และ PM10','home.chart_empty'=>'จะแสดงประวัติหลังเก็บข้อมูล','home.station_status'=>'สถานีทั้งหมด','home.local_network'=>'เครือข่ายเซ็นเซอร์ท้องถิ่น','home.local_empty'=>'ยังไม่มีข้อมูลเซ็นเซอร์ท้องถิ่นล่าสุด','home.sensors_online'=>'เซ็นเซอร์ออนไลน์','home.delayed_sensors'=>'ล่าช้า / ข้อมูลเก่า','home.median_pm25'=>'ค่ามัธยฐาน PM2.5','home.lowest_pm25'=>'ต่ำสุด','home.highest_pm25'=>'สูงสุด','home.median_change'=>'การเปลี่ยนแปลงมัธยฐาน 1 ชั่วโมง','home.forecast_title'=>'ความเสี่ยงจากแบบจำลอง','home.attribution'=>'ข้อมูลแบบจำลองคุณภาพอากาศโดย Open-Meteo.com (CAMS Global)','home.weather_title'=>'บริบทสภาพอากาศ','home.wind'=>'ลม','home.gusts'=>'ลมกระโชก','home.rain'=>'ฝน','home.temperature'=>'อุณหภูมิ','home.weather_unavailable'=>'ไม่มีข้อมูลบริบทสภาพอากาศชั่วคราว','home.weather_attribution'=>'ข้อมูลสภาพอากาศ: Open-Meteo','home.advisory'=>'คำแนะนำรวม',
'station.title'=>'สถานีตรวจวัดคุณภาพอากาศ','station.subtitle'=>'ข้อมูลทางการจาก Air4Thai และข้อมูลเสริมจาก CMU DustBoy ในอำเภอเมืองเชียงใหม่','station.measured'=>'เวลาตรวจวัด','station.set_home'=>'ตั้งเป็นสถานีหลัก','station.view_label'=>'รูปแบบการดู','station.view_list'=>'รายการ','station.view_map'=>'แผนที่','station.map_title'=>'แผนที่สถานี','station.map_note'=>'แผนที่ © ผู้ร่วมสร้าง OpenStreetMap ต้องใช้อินเทอร์เน็ตและไม่บันทึกไทล์','station.history'=>'ประวัติ {code}','station.filter_label'=>'กรองสถานี','station.filter_all'=>'ทั้งหมด','station.filter_official'=>'ทางการ','station.filter_local'=>'ท้องถิ่น','station.official'=>'ทางการ','station.local'=>'เซ็นเซอร์ท้องถิ่น','station.pm25_legend'=>'สีเครื่องหมายท้องถิ่นแสดงความเข้มข้น PM2.5 ไม่ใช่ AQI',
'source.air4thai'=>'Air4Thai / PCD','source.dustboy'=>'CMU DustBoy / CMU CCDC','source.openmeteo_weather'=>'Open-Meteo','pm25.band.low'=>'PM2.5 ต่ำ','pm25.band.moderate'=>'PM2.5 ปานกลาง','pm25.band.high'=>'PM2.5 สูง','pm25.band.very_high'=>'PM2.5 สูงมาก','pm25.band.unknown'=>'ไม่มีค่า PM2.5',
'alerts.title'=>'การแจ้งเตือนคุณภาพอากาศ','alerts.subtitle'=>'เปิดเมื่อมีผลกระทบต่อสุขภาพ ยกระดับทันที และสิ้นสุดหลังต่ำกว่าเกณฑ์ 90 นาที','alerts.none'=>'ยังไม่มีเหตุการณ์แจ้งเตือนคุณภาพอากาศ','alerts.active'=>'กำลังใช้งาน','alerts.cleared'=>'สิ้นสุดแล้ว','push.setting_title'=>'การแจ้งเตือนคุณภาพอากาศ','push.setting_body'=>'รับการแจ้งเตือนระดับมีผลกระทบต่อสุขภาพ ระดับมีผลกระทบต่อสุขภาพมาก และการฟื้นตัวหนึ่งครั้งต่อเหตุการณ์','push.enable'=>'เปิดการแจ้งเตือน','push.disable'=>'ปิดการแจ้งเตือน','push.not_requested'=>'การแจ้งเตือนปิดอยู่','push.enabled'=>'เปิดการแจ้งเตือนแล้ว','push.denied'=>'เบราว์เซอร์บล็อกการแจ้งเตือน','push.unsupported'=>'เบราว์เซอร์นี้ไม่รองรับการแจ้งเตือน','push.install_required'=>'โปรดเพิ่มแอปไปยังหน้าจอโฮมก่อน','push.error'=>'อัปเดตการแจ้งเตือนไม่สำเร็จ',
'air.status.very_good'=>'ดีมาก','air.status.good'=>'ดี','air.status.moderate'=>'ปานกลาง','air.status.unhealthy'=>'เริ่มมีผลกระทบต่อสุขภาพ','air.status.very_unhealthy'=>'มีผลกระทบต่อสุขภาพ','air.status.unknown'=>'ไม่มีค่า AQI','forecast.low'=>'ความเสี่ยง PM2.5 จากแบบจำลองอยู่ในระดับต่ำ','forecast.moderate'=>'ความเสี่ยง PM2.5 จากแบบจำลองอยู่ในระดับปานกลาง','forecast.high'=>'ความเสี่ยง PM2.5 จากแบบจำลองอยู่ในระดับสูง','forecast.very_high'=>'ความเสี่ยง PM2.5 จากแบบจำลองอยู่ในระดับสูงมาก','forecast.unknown'=>'ไม่มีข้อมูลพยากรณ์จากแบบจำลอง','forecast.direction.improving'=>'แบบจำลองคาดว่าสถานการณ์จะดีขึ้น','forecast.direction.worsening'=>'แบบจำลองคาดว่าสถานการณ์จะแย่ลง','forecast.direction.stable'=>'แบบจำลองคาดว่าสถานการณ์ค่อนข้างคงที่','forecast.direction.unknown'=>'ยังประเมินแนวโน้มไม่ได้',
'advisory.normal'=>'ค่าตรวจวัดทางการและแบบจำลองไม่แสดงความเสี่ยงที่เพิ่มขึ้น','advisory.watch'=>'โปรดติดตามข้อมูล เนื่องจากค่าตรวจวัดหรือแบบจำลองสูงขึ้น','advisory.warning'=>'ลดการสัมผัสควันที่หลีกเลี่ยงได้และติดตามประกาศสาธารณสุข','advisory.critical'=>'คุณภาพอากาศแย่มากตามค่าตรวจวัดหรือแบบจำลอง โปรดปฏิบัติตามคำแนะนำทางการ','advisory.unknown'=>'คำแนะนำรวมต้องใช้ค่าตรวจวัดทางการและแบบจำลองล่าสุด','alert.title.unhealthy'=>'คุณภาพอากาศมีผลกระทบต่อสุขภาพ','alert.title.very_unhealthy'=>'คุณภาพอากาศมีผลกระทบต่อสุขภาพมาก','alert.message.unhealthy'=>'สถานีทางการรายงานคุณภาพอากาศที่มีผลกระทบต่อสุขภาพ','alert.message.very_unhealthy'=>'สถานีทางการรายงานคุณภาพอากาศที่มีผลกระทบต่อสุขภาพมาก','alert.message.normal'=>'เหตุการณ์คุณภาพอากาศที่ใช้งานอยู่ฟื้นตัวแล้ว',
'severity.normal'=>'ปกติ','severity.watch'=>'เฝ้าระวัง','severity.warning'=>'เตือน','severity.critical'=>'วิกฤต','severity.unhealthy'=>'มีผลกระทบต่อสุขภาพ','severity.very_unhealthy'=>'มีผลกระทบมาก','severity.unknown'=>'รอข้อมูล','severity.low'=>'ต่ำ','severity.moderate'=>'ปานกลาง','severity.high'=>'สูง','severity.very_high'=>'สูงมาก','freshness.live'=>'สด','freshness.delayed'=>'ล่าช้า','freshness.stale'=>'ข้อมูลเก่า','freshness.offline'=>'ออฟไลน์','freshness.current'=>'ปัจจุบัน','freshness.aging'=>'เริ่มเก่า',
'push.title.unhealthy'=>'เฝ้าระวังอากาศเชียงใหม่ — มีผลกระทบ','push.title.very_unhealthy'=>'เฝ้าระวังอากาศเชียงใหม่ — มีผลกระทบมาก','push.title.cleared'=>'เฝ้าระวังอากาศเชียงใหม่ — ฟื้นตัว','push.body.unhealthy'=>'สถานีทางการรายงานคุณภาพอากาศที่มีผลกระทบต่อสุขภาพ','push.body.very_unhealthy'=>'สถานีทางการรายงานคุณภาพอากาศที่มีผลกระทบต่อสุขภาพมาก','push.body.cleared'=>'เหตุการณ์คุณภาพอากาศฟื้นตัวแล้ว',
'error.title'=>'โหลดข้อมูลไม่ได้','error.body'=>'ข้อมูลคุณภาพอากาศล่าสุดไม่พร้อมใช้งานชั่วคราว','error.api.invalid_station'=>'ไม่รองรับสถานีที่ร้องขอ','error.api.invalid_period'=>'ไม่รองรับช่วงเวลาที่ร้องขอ','error.api.invalid_language'=>'ไม่รองรับภาษาที่ร้องขอ','error.api.station_not_found'=>'ไม่พบสถานีที่ร้องขอ','error.api.method_not_allowed'=>'ไม่รองรับวิธีการร้องขอนี้','error.api.invalid_content_type'=>'ปลายทางนี้ต้องใช้ JSON','error.api.invalid_origin'=>'ไม่อนุญาตแหล่งที่มาของคำขอ','error.api.request_too_large'=>'คำขอใหญ่เกินไป','error.api.invalid_json'=>'JSON ไม่ถูกต้อง','error.api.invalid_subscription'=>'ข้อมูลสมัครรับการแจ้งเตือนไม่ถูกต้อง','error.api.push_disabled'=>'เซิร์ฟเวอร์ยังไม่เปิดการแจ้งเตือน','error.api.rate_limited'=>'มีคำขอมากเกินไป โปรดลองใหม่','error.api.internal'=>'ข้อมูลไม่พร้อมใช้งานชั่วคราว','offline.title'=>'คุณออฟไลน์อยู่','offline.body'=>'เชื่อมต่ออินเทอร์เน็ตเพื่อรับข้อมูลล่าสุด','theme.system'=>'ตามระบบ','theme.light'=>'สว่าง','theme.dark'=>'มืด','theme.change'=>'ธีม: {mode} แตะเพื่อเปลี่ยน'
,'home.humidity'=>'ความชื้น',
];
