<?php
// Senast uppdaterad: 2026-09-05 14:00 Asia/Bangkok | Version 1.11 | KlⒶssⓔ & Ⓐberg
$primary=$dashboard['primary'];$area=$dashboard['area'];$forecast=$dashboard['forecast'];$advisory=$dashboard['advisory'];$local=$dashboard['local_sensor_summary'];$weather=$dashboard['weather'];$status=(string)($area['status']??'unknown');$official=null;foreach($dashboard['stations'] as $candidate)if(($candidate['public_id']??null)===($area['station_public_id']??null)){$official=$candidate;break;}$official??=$primary;$selected=$primary;$selectedOfficial=(bool)($selected['affects_official_status']??true);$selectedSeverity=$selectedOfficial?\ChiangMaiAirWatch\Services\AirQualityEngine::category($selected['source_aqi']??null):\ChiangMaiAirWatch\Services\AirQualityEngine::pm25Band($selected['pm25_ug_m3']??null);
?>
<section class="hero-heading"><p class="eyebrow"><?=e(t('home.eyebrow'))?></p><div><h1><?=e(t('home.title'))?></h1><span class="status-dot"></span></div></section>
<?php if($loadError):?><div class="notice notice-unknown" role="alert"><strong><?=e(t('error.title'))?></strong><span><?=e(t('error.body'))?></span></div><?php endif;?>
<div id="data-stale-banner" class="notice notice-stale" hidden><?=e(t('common.data_stale'))?></div>
<p id="offline-snapshot-time" class="snapshot-time" data-label="<?=e(t('common.saved_at',['time'=>'{time}']))?>" hidden></p>

<section class="risk-card official-area-card severity-<?=e($status)?>">
 <div class="risk-icon"><span class="material-symbols">verified</span></div>
 <div><p class="kicker"><?=e(t('home.official_area_status'))?></p><h2><?=e(t('air.status.'.$status))?><?=is_numeric($area['source_aqi']??null)?' · TH AQI '.e((string)$area['source_aqi']):''?></h2><p><?=e($area['station_name_'.locale()]??t('air.status.unknown'))?> · <?=e(t('source.air4thai'))?></p></div>
</section>

<section class="card chart-card"><div class="card-heading"><div><p class="kicker"><?=e(t('home.official_chart'))?></p><h2><?=e($official['display_name_'.locale()]??t('common.no_data'))?></h2></div><span><?=e(t('common.last_24h'))?></span></div><div class="chart-wrap"><canvas id="air-chart" data-station="<?=e($official['public_id']??'air4thai:36t')?>"></canvas><p id="chart-empty" class="empty" hidden><?=e(t('home.chart_empty'))?></p></div></section>

<section id="selected-station-card" class="card level-card severity-<?=e($selectedSeverity)?>" data-classification="<?=$selectedOfficial?'official':'supplementary'?>" data-label-official="<?=e(t('station.official'))?>" data-label-local="<?=e(t('station.local'))?>" data-label-selected="<?=e(t('home.selected_station'))?>">
 <label class="home-station-picker" for="home-station-select"><span><?=e(t('home.station_picker'))?></span><select id="home-station-select"><?php foreach($dashboard['stations'] as$s):$id=$s['public_id'];?><option value="<?=e($id)?>"<?=($primary['public_id']??'')===$id?' selected':''?>><?=e($s['display_name_'.locale()])?></option><?php endforeach;?></select></label>
 <div class="card-heading"><div><p id="selected-kicker" class="kicker"><?=e(t('home.selected_station'))?> · <?=e(t($selectedOfficial?'station.official':'station.local'))?></p><h2 id="primary-title"><?=e($selected['display_name_'.locale()]??t('common.no_data'))?></h2></div><span id="primary-freshness" class="badge badge-<?=e($selected['freshness_status']??'offline')?>"><?=e(t('freshness.'.($selected['freshness_status']??'offline')))?></span></div>
 <div class="aqi-reading"><span id="primary-reading"><?=e($selectedOfficial?(is_numeric($selected['source_aqi']??null)?(string)$selected['source_aqi']:'—'):format_pollutant($selected['pm25_ug_m3']??null))?></span><small id="primary-reading-label"><?=$selectedOfficial?'TH AQI':'PM2.5 µg/m³'?></small></div>
 <h3 id="primary-category"><?=e($selectedOfficial?t('air.status.'.\ChiangMaiAirWatch\Services\AirQualityEngine::category($selected['source_aqi']??null)):t('pm25.band.'.\ChiangMaiAirWatch\Services\AirQualityEngine::pm25Band($selected['pm25_ug_m3']??null)))?></h3>
 <p id="aqi-unavailable" class="muted"<?=!$selectedOfficial||is_numeric($selected['source_aqi']??null)?' hidden':''?>><?=e(t('home.aqi_unavailable'))?></p>
 <div class="metric-grid three"><div><span>PM2.5</span><strong id="primary-pm25"><?=e(format_pollutant($selected['pm25_ug_m3']??null))?> µg/m³</strong></div><div><span>PM10</span><strong id="primary-pm10"><?=e(format_pollutant($selected['pm10_ug_m3']??null))?> µg/m³</strong></div><div><span><?=e(t('home.change'))?></span><strong id="primary-trend"><?=e(trend_display($selected['change_1h_pm25']??null))?></strong></div></div>
 <p class="muted"><span id="primary-time"><?=e(format_local_time($selected['measured_at']??null))?></span> · <span id="primary-source"><?=e(t('source.'.($selected['provider']??'air4thai')))?></span></p>
</section>

<section class="card local-summary-card"><div class="card-heading"><div><p class="kicker"><?=e(t('home.local_network'))?></p><h2><?=e(t('source.dustboy'))?></h2></div><span class="badge badge-<?=$local['live_count']>0?'live':'offline'?>"><?=e((string)$local['live_count'].' '.t('home.sensors_online'))?></span></div>
<div class="local-summary-grid"<?=$local['valid_pm25_count']>0?'':' hidden'?>><div><span><?=e(t('home.median_pm25'))?></span><strong><?=e(format_pollutant($local['median_pm25']))?> µg/m³</strong></div><div><span><?=e(t('home.lowest_pm25'))?></span><strong><?=e(format_pollutant($local['min_pm25']))?> µg/m³</strong></div><div><span><?=e(t('home.highest_pm25'))?></span><strong><?=e(format_pollutant($local['max_pm25']))?> µg/m³</strong></div><div><span><?=e(t('home.median_change'))?></span><strong><?=e(trend_display($local['median_change_1h']))?></strong></div></div><p class="muted local-empty"<?=$local['valid_pm25_count']>0?' hidden':''?>><?=e(t('home.local_empty'))?></p><p class="muted"><?=e(t('home.valid_pm25_sensors'))?>: <?=e((string)$local['valid_pm25_count'])?> / <?=e((string)$local['live_count'])?> · <?=e(t('home.delayed_sensors'))?>: <?=e((string)($local['delayed_count']+$local['stale_count']))?></p>
</section>

<section class="card"><div class="card-heading"><h2><?=e(t('home.station_status'))?></h2><a href="<?=e(url('stations.php?lang='.locale()))?>"><?=e(t('common.details'))?></a></div><div class="station-rows"><?php foreach($dashboard['stations'] as$s):$officialSource=(bool)$s['affects_official_status'];?><a class="station-row" href="<?=e(url('station.php?code='.rawurlencode($s['public_id']).'&lang='.locale()))?>"><span><strong><?=e($s['display_name_'.locale()])?></strong><small><?=e(t($officialSource?'station.official':'station.local'))?> · <?=e(t('source.'.$s['provider']))?></small></span><span class="station-value"><strong><?=$officialSource?'TH AQI '.e(is_numeric($s['source_aqi']??null)?(string)$s['source_aqi']:'—'):'PM2.5 '.e(format_pollutant($s['pm25_ug_m3']??null))?></strong><small class="badge badge-inline badge-<?=e($s['freshness_status']??'offline')?>"><?=e(t('freshness.'.($s['freshness_status']??'offline')))?></small></span></a><?php endforeach;?></div></section>

<section class="card weather-card"><div class="card-heading"><div><p class="kicker"><?=e(t('common.next_24h'))?></p><h2><?=e(t('home.forecast_title'))?></h2></div><span class="material-symbols weather-symbol">model_training</span></div><div class="forecast-risk severity-<?=e($forecast['severity']??'unknown')?>"><strong><?=e(t('severity.'.($forecast['severity']??'unknown')))?></strong><span><?=e(is_numeric($forecast['windows'][24]['mean']??null)?number_format((float)$forecast['windows'][24]['mean'],1).' µg/m³':t('common.no_data'))?></span></div><p><?=e(t('forecast.direction.'.($forecast['direction']??'unknown')))?></p><p class="attribution"><a href="https://open-meteo.com/en/docs/air-quality-api" rel="external noopener"><?=e(t('home.attribution'))?></a></p></section>

<section class="card context-card"><div class="card-heading"><div><p class="kicker"><?=e(t('home.weather_title'))?></p><h2><?=e(t('home.weather_attribution'))?></h2></div><span class="material-symbols weather-symbol">air</span></div><div class="weather-context-grid"<?=$weather?'':' hidden'?>><div><span><?=e(t('home.wind'))?></span><strong><?=e($weather['wind_direction_compass']??'—')?> <?=e(format_pollutant($weather['wind_speed_kmh']??null))?> km/h</strong></div><div><span><?=e(t('home.gusts'))?></span><strong><?=e(format_pollutant($weather['wind_gust_kmh']??null))?> km/h</strong></div><div><span><?=e(t('home.rain'))?></span><strong><?=e(format_pollutant($weather['precipitation_mm']??null))?> mm</strong></div><div><span><?=e(t('home.temperature'))?></span><strong><?=e(format_pollutant($weather['temperature_c']??null))?> °C</strong></div></div><p class="muted"><?=e($weather?t('common.updated',['time'=>format_local_time($weather['observed_at'])]):t('home.weather_unavailable'))?></p></section>

<section class="advisory severity-<?=e($advisory['severity']??'unknown')?>"><span class="material-symbols">campaign</span><div><p class="kicker"><?=e(t('home.advisory'))?></p><h2><?=e(t('severity.'.($advisory['severity']??'unknown')))?></h2><p><?=e(t($advisory['message_key']??'advisory.unknown'))?></p></div></section>
<p class="updated"><?=e(t('common.updated',['time'=>format_local_time($dashboard['generated_at'])]))?></p>
