<?php
// Senast uppdaterad: 2026-09-03 14:10 Asia/Bangkok | Version 1.10 | KlⒶssⓔ & Ⓐberg
?>
<section class="page-heading"><h1><?=e(t('station.title'))?></h1><p><?=e(t('station.subtitle'))?></p></section>
<?php if($loadError):?><div class="notice notice-unknown"><strong><?=e(t('error.title'))?></strong></div><?php endif;?>
<div class="station-view-toggle" role="group" aria-label="<?=e(t('station.view_label'))?>"><button type="button" data-station-view="list" aria-pressed="true"><?=e(t('station.view_list'))?></button><button type="button" data-station-view="map" aria-pressed="false"><?=e(t('station.view_map'))?></button></div>
<div class="provider-filter" role="group" aria-label="<?=e(t('station.filter_label'))?>"><?php foreach(['all','official','local'] as$filter):?><button type="button" data-provider-filter="<?=e($filter)?>" aria-pressed="<?=$filter==='all'?'true':'false'?>"><?=e(t('station.filter_'.$filter))?></button><?php endforeach;?></div>
<section data-view-panel="map" hidden><div class="card map-card"><h2><?=e(t('station.map_title'))?></h2><div id="station-map" class="station-map" data-tile-url="<?=e((string)\ChiangMaiAirWatch\Config::get('maps.tile_url'))?>" data-details-label="<?=e(t('common.details'))?>" data-official-label="<?=e(t('station.official'))?>" data-local-label="<?=e(t('station.local'))?>" data-updated-label="<?=e(t('common.updated',['time'=>'{time}']))?>"></div><p class="map-legend"><span class="legend-shape official"></span><?=e(t('station.filter_official'))?> <span class="legend-shape local"></span><?=e(t('station.filter_local'))?></p><p><?=e(t('station.pm25_legend'))?></p><p><?=e(t('station.map_note'))?></p></div></section>
<div id="map-station-data" hidden><?php foreach($stations as$s):$official=(bool)$s['affects_official_status'];?><span data-map-station="<?=e($s['public_id'])?>" data-classification="<?=$official?'official':'local'?>" data-name="<?=e($s['display_name_'.locale()])?>" data-source="<?=e(t('source.'.$s['provider']))?>" data-latitude="<?=e((string)$s['latitude'])?>" data-longitude="<?=e((string)$s['longitude'])?>" data-aqi="<?=e((string)($s['source_aqi']??''))?>" data-pm25="<?=e((string)($s['pm25_ug_m3']??''))?>" data-pm10="<?=e((string)($s['pm10_ug_m3']??''))?>" data-status="<?=$official?e(\ChiangMaiAirWatch\Services\AirQualityEngine::category($s['source_aqi']??null)):e(\ChiangMaiAirWatch\Services\AirQualityEngine::pm25Band($s['pm25_ug_m3']??null))?>" data-freshness="<?=e($s['freshness_status']??'offline')?>" data-time="<?=e($s['measured_at']??'')?>" data-url="<?=e(url('station.php?code='.rawurlencode($s['public_id']).'&lang='.locale()))?>"></span><?php endforeach;?></div>
<section data-view-panel="list"><div class="stations-grid"><?php foreach($stations as$s):$official=(bool)$s['affects_official_status'];?><article class="card station-card" data-provider-card="<?=$official?'official':'local'?>"><div class="card-heading"><div><p class="kicker"><?=e(t($official?'station.official':'station.local'))?> · <?=e(t('source.'.$s['provider']))?></p><h2><?=e($s['display_name_'.locale()])?></h2></div><span class="badge badge-<?=e($s['freshness_status']??'offline')?>"><?=e(t('freshness.'.($s['freshness_status']??'offline')))?></span></div><div class="aqi-reading compact"><span><?=e($official?(is_numeric($s['source_aqi']??null)?(string)$s['source_aqi']:'—'):format_pollutant($s['pm25_ug_m3']??null))?></span><small><?=$official?'TH AQI':'PM2.5 µg/m³'?></small></div><?php if(!$official):?><p class="local-band"><?=e(t('pm25.band.'.\ChiangMaiAirWatch\Services\AirQualityEngine::pm25Band($s['pm25_ug_m3']??null)))?></p><?php endif;?><div class="metric-grid two"><div><span><?=$official?'PM2.5':'PM10'?></span><strong><?=e(format_pollutant($s[$official?'pm25_ug_m3':'pm10_ug_m3']??null))?> µg/m³</strong></div><div><span><?=e(t('station.measured'))?></span><strong><?=e(format_local_time($s['measured_at']??null))?></strong></div></div><div class="station-actions"><button class="secondary-button home-station-button" data-code="<?=e($s['public_id'])?>"><?=e(t('station.set_home'))?></button><a class="button-link" href="<?=e(url('station.php?code='.rawurlencode($s['public_id']).'&lang='.locale()))?>"><?=e(t('common.details'))?></a></div></article><?php endforeach;?></div></section>
